parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\GraphQl\Entry\Query\QueryEntryInterface:
            tags: ['graphql.schema.query.field']

        App\Manager\User\UserManagerAwareInterface:
            calls:
                -   method: setUserManager
                    arguments:
                        - '@App\Manager\User\UserManager'


    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Api\:
        resource: '../src/Api'
        tags: ['controller.service_arguments']

    App\GraphQl\Query\QueryInterface:
        class: App\GraphQl\Query\Query
